# LAB 1-1

> **Task**

**You are given two integer arrays, A and B of dimensions NxM.**

1. Your task is to perform the following operations:

* Add ( A+B )
* Subtract ( A-B )
* Multiply ( A*B )
* Integer Division ( A/B )
* Mod ( A%B )
* Power ( A**B )

In [1]:
import numpy as np

# Input handling
N, M = map(int, input().split())

A = np.array([list(map(int, input().split())) for _ in range(N)])
B = np.array([list(map(int, input().split())) for _ in range(N)])

# Operations
addition = A + B
subtraction = A - B
multiplication = A * B
integer_division = np.floor_divide(A, B)
modulus = A % B
power = A ** B

# Output the results
print(addition)
print(subtraction)
print(multiplication)
print(integer_division)
print(modulus)
print(power)


1 4
1 2 3 4 
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# LAB 2-1

> **Task**

**You are given a NxM integer array matrix with space separated elements ( M= rows and N= columns).**

1. Your task is to print the transpose and flatten results.

In [2]:
import numpy as np

# Input handling
N, M = map(int, input().split())

# Read the matrix
matrix = np.array([input().split() for _ in range(N)], int)

# Transpose the matrix
transpose_matrix = np.transpose(matrix)

# Flatten the matrix
flatten_matrix = matrix.flatten()

# Print the results
print(transpose_matrix)
print(flatten_matrix)


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# LAB 3-1

> **Task**

**You are given a 2-D array of size NXM.**

1. Your task is to find:
* The mean along axis 1
* The var along axis 0
* The std along axis None

In [3]:
import numpy as np

# Input handling
N, M = map(int, input().split())

# Read the matrix
matrix = np.array([input().split() for _ in range(N)], int)

# Compute the required statistics
mean_axis1 = np.mean(matrix, axis=1)
var_axis0 = np.var(matrix, axis=0)
std_none = np.std(matrix, axis=None)

# Print the results
print(mean_axis1)
print(var_axis0)
print(std_none)


2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


# LAB 4-1

> **Task**

**You are given the coefficients of a polynomial P.**

1. Your task is to find the value of P at point x.

In [4]:
import numpy as np

# Input handling
coefficients = list(map(float, input().split()))
x = float(input())

# Evaluate the polynomial at x
result = np.polyval(coefficients, x)

# Print the result
print(result)


1.1 2 3
0
3.0


# LAB 5-1

> **Task**

**Slice and index the random_array then Perform the following:**

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

In [7]:
import numpy as np

# Create a random 2-D array with a specified size
np.random.seed(0)  # Set seed for reproducibility
random_array = np.random.randint(1, 10, size=(5, 5))

# Print the random array for reference
print("Random Array:")
print(random_array)

# 1. Grab the first two rows of the array
first_two_rows = random_array[:2, :]
print("\nFirst two rows:")
print(first_two_rows)

# 2. Grab the entire first column
first_column = random_array[:, 0]
print("\nFirst column:")
print(first_column)

# 3. Grab the second element of the third row
second_element_third_row = random_array[2, 1]
print("\nSecond element of the third row:")
print(second_element_third_row)


Random Array:
[[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]

First two rows:
[[6 1 4 4 8]
 [4 6 3 5 8]]

First column:
[6 4 7 8 9]

Second element of the third row:
9


# LAB 6-1

> **Task**

**We need to create an algorithm to apply a random discount to a list of prices.**

Follow these steps to complete the task:

* Add a Shipping Fee
* Create a Random Discount Array
* Apply Discounts to Prices
* Output the Results


In [8]:
import numpy as np

# Step 1: Add a Shipping Fee
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
shipping_fee = 5.0
total = prices + shipping_fee

# Step 2: Create a Random Discount Array
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3, 3)

# Step 3: Apply Discounts to Prices
discount_pct = random_array.flatten()[:6]
pct_owed = 1 - discount_pct
final_owed = np.round(pct_owed * total, 2)

# Step 4: Output the Results
print("discount_pct:", discount_pct)
print("pct_owed:", pct_owed)
print("final_owed:", final_owed)


discount_pct: [0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]
pct_owed: [0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]
final_owed: [ 8.27 10.88 10.67 98.62  3.39 13.46]
